# Copyright IBM Corp. All Rights Reserved.
# modified Nobuyuki Matsui <nobuyuki.matsui@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0
#

Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/example.com/msp
    - &Org1
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
        AnchorPeers:
            - Host: peer0
              Port: 7051
            - Host: peer1
              Port: 7051
            - Host: peer2
              Port: 7051
            - Host: peer3
              Port: 7051

Orderer: &OrdererDefaults
    OrdererType: kafka
    Addresses:
        - orderer0:7050
        - orderer1:7050
        - orderer2:7050
        - orderer3:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    kafka:
      Brokers:
        - kafka0:9092
        - kafka1:9092
        - kafka2:9092
        - kafka3:9092
    Organizations:

Application: &ApplicationDefaults
    Organizations:

Profiles:
    OneOrgFourOrderersGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            FabricPaymentSampleConsortium:
                Organizations:
                    - *Org1
    OneOrgFourOrderersChannel:
        Consortium: FabricPaymentSampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
